### ISSUE TITLE
new prompts

### ISSUE THREAD

**Issue by thraxil** [thraxil/countryx#151]
mentioned by tucker. need more details

**Comment by tuckerharding** [comment]
"Please describe the elements or factors that made this the most appealing
decision at this time in this scenario."

**Comment by tuckerharding** [comment]
server error-- holy. in the final turn

**Comment by tuckerharding** [comment]
any quick fix?

**Comment by tuckerharding** [comment]
when we updated to the final result, final outcome, every user received a
500. i can still log in as admin.

**Comment by tuckerharding** [comment]
interestingly, i can still see the final outcome for each group. but none
of the logins seem to work right now besides admin.

little bit of a hot seat at the moment.
