### ISSUE TITLE
500 when creating new section and groups

### ISSUE THREAD

**Issue by thraxil** [thraxil/countryx#162]
> While still logged as "tucker", I got a 500 error when attempting to create a new section and groups. The first time it happened i used a1, a2 etc. and thought maybe reusing the usernames from the demo course could cause an issue. But the second time I used d1, d2, d3 and still received the error.

probably related to this: https://opbeat.com/thraxil/countryx/errors/3/

**Comment by thraxil** [comment]
Model defines `max_length` on `Section.name` to be 40 chars, but database still has it as 20 for some reason. I'll probably just bump it to 256, but it's curious that the db and model are not in sync. Probably something weird happened pre-migrations.

**Comment by tuckerharding** [comment]
OK cool, will keep testing.

Mark sent our survey drafts finally--he's flying to NYC today. I will get
in there, edit and send you the link in an hour or so once I'm in the
office.

**Comment by tuckerharding** [comment]
Works fine now.
